services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_vector_db
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT_SERVICE_GRPC_PORT: 6334
      QDRANT_SERVICE_HTTP_PORT: 6333
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: chatbot_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - qdrant
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  qdrant_data:
