version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_vector_db
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT_SERVICE_GRPC_PORT: 6334
      QDRANT_SERVICE_HTTP_PORT: 6333

  backend:
    build: .
    container_name: chatbot_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      mysql:
        condition: service_healthy
      qdrant:
        condition: service_started
      redis:
        condition: service_healthy
    environment:
      QDRANT_URL: http://qdrant:6333/
      QDRANT_COLLECTION: company_kb
      RAG_TOP_K: 3
      RAG_SCORE_THRESHOLD: 0.7
      FRONTEND_ORIGIN: http://localhost:5173/
      DB_HOST: mysql
      DB_USER: valen
      DB_PASSWORD: valen
      DB_NAME: chatbot_db
      DB_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: >
      sh -c "echo 'Esperando a que MySQL esté listo...' &&
             sleep 10 &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: chatbot_db
      MYSQL_USER: valen
      MYSQL_PASSWORD: valen
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  redis:
    image: redis:7.2        # 👈 Redis como contenedor
    container_name: chatbot_redis
    ports:
      - "6379:6379"         # 👈 expuesto al host, opcional
    volumes:
      - redis_data:/data    # 👈 persistencia de datos
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  qdrant_data:
  mysql_data:
  redis_data:
